ws_coraltec_homepage:
    path:     /
    defaults: { _controller: WSCoraltecBundle:Default:index }

defalt_contact:
    path:     /contact
    defaults: { _controller: WSCoraltecBundle:Default:contact }

defalt_about:
    path:     /about
    defaults: { _controller: WSCoraltecBundle:Default:about }

defalt_servic:
    path:     /service
    defaults: { _controller: WSCoraltecBundle:Default:service }